apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mychart-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: general
    notifications.argoproj.io/subscribe.on-sync-failed.slack: general
    notifications.argoproj.io/subscribe.on-health-degraded.slack: general
    notifications.argoproj.io/subscribe.on-health-succeeded.slack: general
spec:
  project: default
  source:
    repoURL: https://github.com/myrondev/argo_test_demo.git
    targetRevision: HEAD
    path: nginx/helm/mychart
    helm:
      parameters:
        - name: nginx.replicaCount
          value: "2"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true