apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/myrondev/argo_test_demo.git
    targetRevision: HEAD
    path: nginx/learning
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd