apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/metrics-server
    repoURL: https://github.com/kubernetes-sigs/metrics-server.git
    targetRevision: HEAD
    helm:
      values: |
        args:
        - --kubelet-insecure-tls=true
        - --metric-resolution=40s
      # parameters:
      #   - name: defaultArgs[3]
      #     value: "--metric-resolution=40s"
  syncPolicy:
      automated: false
      prune: true


      # - --secure-port=10250
        # - --cert-dir=/tmp
        # - --kubelet-preferred-address-types=InternalIP
        # - /metrics-server
        # - --kubelet-use-node-status-port
        # - --metric-resolution=15s - --requestheader-client-ca-file