apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: test-clusterrole
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["get", "namespaces"]
    verbs: ["list"]
