apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-nginx-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "250Mi"
            cpu: "250m"
